export const ACTION_TYPES = {
	ADD_HEAD_WARNING: 'APP/ADD_HEAD_WARNING',
	CLEAR_HEAD_WARNING: 'APP/CLEAR_HEAD_WARNING',
	IS_AUTH: 'PRELOAD/IS_AUTH',
	IS_NOT_AUTH: 'PRELOAD/IS_NOT_AUTH',
	IS_VERIFIED: 'PRELOAD/IS_VERIFIED',
	IS_NOT_VERIFIED: 'PRELOAD/IS_NOT_VERIFIED',
	IS_FIRST_DATA_LOAD: 'PRELOAD/IS_FIRST_DATA_LOAD',
	IS_NOT_FIRST_DATA_LOAD: 'PRELOAD/IS_NOT_FIRST_DATA_LOAD',
	SET_USER_DATA: 'USER/GET_USER_DATA',
	CHANGE_SIGN_IN_DATA: 'SIGN-IN/CHANGE_SIGN_IN_DATA',
	CHANGE_SIGN_UP_DATA: 'SIGN-UP/CHANGE_SIGN_UP_DATA',
	SET_VERIFICATION_REQUESTS: 'ADMIN/SET_VERIFICATION_REQUESTS',
	SET_SCORE_DRAFT: 'ADMIN/SET_SCORE_DRAFT',
	SET_SCORES_DATA: 'SCORES/SET_SCORES_DATA',
	APPEND_SCORES: 'SCORES/APPEND_SCORES',
	SET_SEARCH_DATA: 'SEARCH/SET_SEARCH_DATA',
	CHANGE_DOWNLODING_DATA: 'FILELOAD/CHANGE_DOWNLODING_DATA',
	CHANGE_ADD_DATA: 'ADS/CHANGE_ADD_DATA',
	SET_ADS_DATA: 'ADS/SET_ADS_DATA'
}

export const HEAD_WARNING_TYPES = {
	ERROR: 'darkred',
	INFO: 'darkgoldenrod',
	SUCCES: 'darkgreen',
}
